Voroshil_photo=[
"encyclopedia_voroshilovsky_guestion_1","encyclopedia_voroshilovsky_guestion_2","encyclopedia_voroshilovsky_guestion_3","encyclopedia_voroshilovsky_guestion_4","encyclopedia_voroshilovsky_guestion_5",
    "encyclopedia_voroshilovsky_guestion_6","encyclopedia_voroshilovsky_guestion_7","encyclopedia_voroshilovsky_guestion_8","encyclopedia_voroshilovsky_guestion_9","encyclopedia_voroshilovsky_guestion_10",
"encyclopedia_voroshilovsky_guestion_11","encyclopedia_voroshilovsky_guestion_12","encyclopedia_voroshilovsky_guestion_13","encyclopedia_voroshilovsky_guestion_14","encyclopedia_voroshilovsky_guestion_15",
"encyclopedia_voroshilovsky_guestion_16",
]
max_vor=len(Voroshil_photo)